name: Build RMK firmware
on:
  workflow_dispatch:
  push:
    paths:
      - "keyboard.toml"
      - "vial.json"

jobs:
  build:
    uses: HaoboGu/rmk-project-template/.github/workflows/user_build.yml@master